kind: pipeline
type: ssh
name: deploy_prod_backend

server:
  host:
    from_secret: ssh_host_prod
  user: root
  password:
    from_secret: ssh_password_prod

steps:
  - name: deploy
    environment:
      SG_SECRETS:
        from_secret: sg_secrets
      COMPOSE_PROJECT_NAME: webservicesjitcom
      MYSQL_ROOT_PASSWORD:
        from_secret: mysql_root_password
    commands:
      - docker compose -f SGBackend/docker-compose_prod.yaml build
      - docker compose -f SGBackend/docker-compose_prod.yaml up -d

trigger:
  branch:
    - master
  event:
    - push

