version: "3.9"

services:
  sg-backend:
    restart: always
    build: .
    entrypoint: [ "dotnet", "SGBackend.dll", "--environment=Production" ]
    environment:
      - SG_SECRETS=${SG_SECRETS}
    networks:
      - jitcom_net
    ports:
      - "188.68.62.150:4214:80"
    logging:
      driver: "loki"
      options:
        loki-url: ${loki_sink}
        loki-retries: 3
  sg-sql:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${SQL_ROOT_PASSWORD}
      - POSTGRES_DB=sg
    ports:
      - "188.68.62.150:5410:5432"
    volumes:
      - v-postgres:/var/lib/postgresql
    networks:
      - jitcom_net
    logging:
      driver: "loki"
      options:
        loki-url: ${loki_sink}
        loki-retries: 3

volumes:
  v-postgres:

networks:
  jitcom_net:
    external: true