version: "3.9"

# create a local db to which the backend can connect
# (dotnet run)
services:
  sg-mysql:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sg
    ports:
      - "5432:5432"
    volumes:
      - v-postgres:/var/lib/postgresql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
      
volumes:
  v-postgres:
    