version: "3.9"

services:
  dev-sg-backend:
    restart: always
    build: .
    entrypoint: [ "dotnet", "SGBackend.dll", "--environment=DevStage" ]
    environment:
      - SG_SECRETS=${SG_SECRETS}
    networks:
      - jitcom_net
    logging:
      driver: "loki"
      options:
        loki-url: ${loki_sink}
        loki-retries: 3
  dev-sg-sql:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${SQL_ROOT_PASSWORD}
      - POSTGRES_DB=sg
    ports:
      - "188.68.62.150:5411:5432"
    networks:
      - jitcom_net
    logging:
      driver: "loki"
      options:
        loki-url: ${loki_sink}
        loki-retries: 3

networks:
  jitcom_net:
    external: true