version: "3.9"

services:
  sg-backend:
    restart: always
    build: .
    entrypoint: [ "dotnet", "SGBackend.dll", "--environment=Production" ]
    environment:
      - SG_SECRETS=${SG_SECRETS}
    networks:
      - jitcom_net
    logging:
      driver: "loki"
      options:
        loki-url: ${loki_sink}
        loki-retries: 3
  sg-mysql:
    restart: always
    image: mysql:8.0.26
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=sg
      - MYSQL_ROOT_HOST=%
    ports:
      - "188.68.62.150:3310:3306"
    volumes:
      - v-sg-mysql:/var/lib/mysql
    networks:
      - jitcom_net
    logging:
      driver: "loki"
      options:
        loki-url: ${loki_sink}
        loki-retries: 3

volumes:
  v-sg-mysql:
    
networks:
  jitcom_net:
    external: true